apiVersion: apps/v1
kind: Deployment
metadata:
  name: ticketservice
  namespace: ticketservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ticketservice
  template:
    metadata:
      labels:
        app: ticketservice
    spec:
      containers:
      - name: ticketservice
        image: docker.io/krishalika/tickets:latest
        ports:  # port mapping
        - containerPort: 8000 # port number of the container
        envFrom: # environment variables from ConfigMap
          - configMapRef:
                name: ticketservice-configmap # name of the ConfigMap object

